### ISSUE TITLE
method

### ISSUE THREAD

**Issue by Yansong-weilab** [ShawnWx2019/WGCNA-shinyApp#4]

**Comment by Yansong-weilab** [comment]
/
<img width="1273" alt="WGCNA" src="https://github.com/ShawnWx2019/WGCNA-shinyApp/assets/151906348/5de8234f-7fc6-4637-9613-c84e88520050">在这一步没有显示模块基因和表型的相关性

**Comment by ShawnWx2019** [comment]
这种情况一般是材料命名规则的问题，比如sample_name中包含了空格，-等特殊字符，read.table读入R作为colname的时候会将这些特殊字符转译成. 比如你准备的表达量矩阵表格为：

GeneID | sample 01 | sample 02 | sample 03 
---|---|---|---
Gene01|123|345|3345
Gene02|123|2|123|

read.table读入R之后会变为

GeneID | sample.01 | sample.02 | sample.03 
---|---|---|---
Gene01|123|345|3345
Gene02|123|2|123|

但是trait data读入R后sample id作为column不会被转义

sample_id | normal|hot|cold
---|---|---|---
sample 01|1|0|0
sample 02|0|1|0
sample 03|0|0|1

这样在计算相关性的时候根据表达量矩阵计算的eigengen矩阵的sample id的为`sample.01 sample.02 sample.03`, 而表型数据的sample id 为 `sample 01 sample 02 sample 03`, 这两项不匹配，所以都是NA。

要解决这个问题，要么将表达量矩阵中sample name规范化，不要用特殊字符，比如改写成`sample_01 sample_02 sample_03`, 下划线`_`是不会被转义的，要么将traitdata中的sample id中的特殊字符都换成.， 总之统一一下就不会出错了

**Comment by ShawnWx2019** [comment]
*Auto translated by GPT3*


The issue here is typically related to the naming conventions of the data. For example, if the `sample_name` contains spaces, hyphens, or other special characters, the `read.table` function in R may interpret these special characters as periods when assigning them as column names. For instance, if your expression matrix table looks like this:

```plaintext
| GeneID | sample 01 | sample 02 | sample 03 |
|--------|-----------|-----------|-----------|
| Gene01 | 123       | 345       | 3345      |
| Gene02 | 123       | 2         | 123       |
```

After reading into R using `read.table`, it will become:

```plaintext
| GeneID | sample.01 | sample.02 | sample.03 |
|--------|-----------|-----------|-----------|
| Gene01 | 123       | 345       | 3345      |
| Gene02 | 123       | 2         | 123       |
```

However, when reading trait data into R, the sample ID is not escaped as a column name:

```plaintext
| sample_id | normal | hot | cold |
|-----------|--------|-----|------|
| sample 01 | 1      | 0   | 0    |
| sample 02 | 0      | 1   | 0    |
| sample 03 | 0      | 0   | 1    |
```

So, when calculating correlations, the sample IDs in the eigengene matrix calculated from the expression matrix are `sample.01`, `sample.02`, `sample.03`, while the sample IDs in the phenotype data are `sample 01`, `sample 02`, `sample 03`. These do not match, resulting in NA values.

To address this issue, you can either standardize the sample names in the expression matrix by avoiding special characters, for example, rewrite them as `sample_01`, `sample_02`, `sample_03` (underscores are not escaped). Alternatively, you can replace special characters in the sample IDs of the trait data with periods. In summary, ensure consistency in naming conventions to avoid errors.

**Comment by YJchen1222** [comment]
您好，我也在Module-Traits Relationship 此步驟遇到問題。
我的問題是點選start analysis後，網頁沒有任何反應，TBtools-II跳出對話框顯示finished。
我已經檢查過任何輸入進去的數據，請問會是什麼原因導致的呢?

**Comment by ShawnWx2019** [comment]
> 您好，我也在Module-Traits Relationship 此步驟遇到問題。 我的問題是點選start analysis後，網頁沒有任何反應，TBtools-II跳出對話框顯示finished。 我已經檢查過任何輸入進去的數據，請問會是什麼原因導致的呢?

报错后将debug dialog中的信息粘贴过来

<img width="651" alt="image" src="https://github.com/ShawnWx2019/WGCNA-shinyApp/assets/46912113/c2fa22fd-0b53-416a-90fe-59f52651577b">

**Comment by YJchen1222** [comment]
您好，以下為debug Dialog 的訊息，感謝您的回覆。

3月 14, 2024 2:24:22 下午 biocjava.GUIexcutors.TBtools$19 actionPerformed
嚴重: null
java.io.FileNotFoundException: C:\Users\User\Desktop\TBtools.Report.html (系統找不到指定的路徑。)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:187)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:96)
	at biocjava.GUIexcutors.TBtools.runningReport(TBtools.java:220)
	at biocjava.GUIexcutors.TBtools$19.actionPerformed(TBtools.java:1939)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6632)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6397)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5008)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by ShawnWx2019** [comment]
> 您好，後來仔細檢查trait data format有問題，才出現此問題。 感謝您的回覆。

嗯 后续会更新，目前只接受tab分割的txt，后续会通过bruceR import 函数自动判断类型来导入。等我有时间了更新一波吧....😂

**Comment by Xueliang24** [comment]
大佬，发现R在读取时，如果列明为数字开头会自动加上x

**Comment by ShawnWx2019** [comment]
> 大佬，发现R在读取时，如果列明为数字开头会自动加上x

是的，所以这里需要手动修改下sample_id
